\i films2.sql

ALTER TABLE films ALTER COLUMN title SET NOT NULL;
ALTER TABLE films ALTER COLUMN year SET NOT NULL;
ALTER TABLE films ALTER COLUMN genre SET NOT NULL;
ALTER TABLE films ALTER COLUMN director SET NOT NULL;
ALTER TABLE films ALTER COLUMN duration SET NOT NULL;

ALTER TABLE films ADD CONSTRAINT title_unique UNIQUE (title);

ALTER TABLE films DROP CONSTRAINT title_unique;

ALTER TABLE films
  ADD CONSTRAINT title_length
  CHECK (length(title) >= 1);

